### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by serhack**

### CODE REVIEW

**Comment by serhack** [comment]
?

**Comment by DavidSimalDelVal** [comment]
This complement was modified for the Geldum currency and is not functional with the current version of monero.

**Comment by serhack** [comment]
Part of the code from Monero Integrations is used here. Apply the license.

**Comment by DavidSimalDelVal** [comment]
and if I put both. I think it's the fairest thing.

**Comment by serhack** [comment]
You should :- )

**Pull request closed without merging**
